#for test
version: "3"

services:
  box1:
    image: box:v1.2
    ports:
      - "1883"
    environment:
      - BOXID=1
      - NODEIP=192.168.1.205
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker1

  box2:
    image: box:v1.2
    ports:
      - "1883"
    environment:
      - BOXID=2
      - NODEIP=192.168.1.205
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker1

  box3:
    image: box:v1.1
    environment:
      - BOXID=3
      - NODEIP=192.168.1.205
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker1

  box4:
    image: box:v1.1
    environment:
      - BOXID=4
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box5:
    image: box:v1.1
    environment:
      - BOXID=5
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box6:
    image: box:v1.1
    environment:
      - BOXID=6
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box7:
    image: box:v1.1
    environment:
      - BOXID=7
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box8:
    image: box:v1.1
    environment:
      - BOXID=8
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box9:
    image: box:v1.1
    environment:
      - BOXID=9
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box10:
    image: box:v1.1
    environment:
      - BOXID=10
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box11:
    image: box:v1.1
    environment:
      - BOXID=11
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box12:
    image: box:v1.1
    environment:
      - BOXID=12
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box13:
    image: box:v1.1
    environment:
      - BOXID=13
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box14:
    image: box:v1.1
    environment:
      - BOXID=14
      - NODEIP=192.168.1.206
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker2

  box15:
    image: box:v1.1
    environment:
      - BOXID=15
      - NODEIP=192.168.1.207
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker3

  box16:
    image: box:v1.1
    environment:
      - BOXID=16
      - NODEIP=192.168.1.207
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker3

  box17:
    image: box:v1.1
    environment:
      - BOXID=17
      - NODEIP=192.168.1.207
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker3

  box18:
    image: box:v1.1
    environment:
      - BOXID=18
      - NODEIP=192.168.1.207
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker3

  box19:
    image: box:v1.1
    environment:
      - BOXID=19
      - NODEIP=192.168.1.207
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker3

  box20:
    image: box:v1.1
    environment:
      - BOXID=20
      - NODEIP=192.168.1.207
    deploy:
      placement:
        constraints:
          - node.labels.worker == worker3
