apiVersion: apps/v1
kind: Deployment
metadata:
  name: box1
  namespace: edge-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: box1
  template:
    metadata:
      labels:
        app: box1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1
      containers:
      - name: box1
        image: docker.io/16hz/box:latest
        env:
        - name: BOXID
          value: "1"
        - name: NODEIP
          value: "192.168.1.233"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: box2
  namespace: edge-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: box2
  template:
    metadata:
      labels:
        app: box2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker2
      containers:
      - name: box2
        image: docker.io/16hz/box:latest
        env:
        - name: BOXID
          value: "2"
        - name: NODEIP
          value: "192.168.1.233"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: box3
  namespace: edge-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: box3
  template:
    metadata:
      labels:
        app: box3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker3
      containers:
      - name: box3
        image: docker.io/16hz/box:latest
        env:
        - name: BOXID
          value: "3"
        - name: NODEIP
          value: "192.168.1.233"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: box4
  namespace: edge-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: box4
  template:
    metadata:
      labels:
        app: box4
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker2
      containers:
      - name: box4
        image: docker.io/16hz/box:latest
        env:
        - name: BOXID
          value: "4"
        - name: NODEIP
          value: "192.168.1.233"

