apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod
  namespace: edge-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1
      containers:
      - name: box1
        image: docker.io/16hz/box:latest
        env:
        - name: BOXID
          value: "1"
        - name: NODEIP
          value: "192.168.1.233"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod
  namespace: edge-box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1
      containers:
      - name: box2
        image: docker.io/16hz/box:latest
        env:
        - name: BOXID
          value: "2"
        - name: NODEIP
          value: "192.168.1.233"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: edge-box
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker1
  containers:
  - name: box2
    image: docker.io/16hz/box:v1.2
    env:
    - name: BOX
      value: "2"
    - name: NODE
      value: "192.168.1.233"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  namespace: edge-box
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker2
  containers:
  - name: box3
    image: docker.io/16hz/box:v1.2
    env:
    - name: BOX
      value: "3"
    - name: NODE
      value: "192.168.1.233"
